# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lalafell Mansion
email: LiaLala@lalamail.net
description: > # this means to ignore newlines until "baseurl:"
 Lalafell website btw
baseurl: "/lala" # the subpath of your site, e.g. /blog 

url: "http://www.lalasite.com" # the base hostname & protocol for your site
twitter_username: sis_kisses
github_username:  YellowDellow

# Build settings
markdown: kramdown
